import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import MainNavbar from "./_components/mainNavbar";

const inter = Inter({ subsets: ["latin"] });
console.log("woi")
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col md:flex-row">
        <ChakraProvider>
        {children}
        </ChakraProvider>
        </body>
    </html>
  );
}
